# Generated by Django 4.2.10 on 2024-02-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_pin_pinlat_pin_pinlong'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
