# Generated by Django 4.2.10 on 2024-02-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_pin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='pinDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
