# Generated by Django 4.2.10 on 2024-02-26 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_pin_pindate_alter_pin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pinDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 22, 12, 42, 661694)),
        ),
    ]
