# Generated by Django 4.2.10 on 2024-02-26 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0005_alter_pin_pindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pinDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
